# Site settings
title: Bare Knuckle Programming
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Yet another programming blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://johnmcconnell.github.io" # the base hostname & protocol for your site
twitter_username: none
github_username:  johnmcconnell

# Build settings
markdown: kramdown
