# Site settings
title: Bare Knuckle Programming
email: johnnyillinois@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Yet another programming blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://johnmcconnell.github.io" # the base hostname & protocol for your site
github_username:  johnmcconnell

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
