# Welcome to Jekyll!

# Website settings
title: "John McConnell"
description: "My Blog"
keywords: "John,McConnell,blog,software,develop,software engineering"

baseurl: "/"
url: "http://www.johnmcconnell.github.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'John'
  first_name: 'John'
  last_name: 'McConnell'
  email: '#'
  facebook_username: '#'
  github_username: 'johnmcconnell'
  head_img: 'static/img/landing/404.jpg'

# social link
john:
  first_name: 'John'
  last_name: 'McConell'
  description: 'Do not know'
  link: ''
  email: ''

# landing page
landing:
  home: 'Home'
  about: 'About'
  cv: 'CV'
  transcript: 'Transcript'
  career: 'Career'
  skills: 'Skills'
  projects: 'Project'
  blog: 'Blog'
  contact: 'Link'

# my projects
project:
  saplatform:
    name: 'Saplatform'
    url: '/Jack614/saplatform'
    img: 'static/img/landing/saplatform.jpg'
  jalpc:
    name: 'Jalpc'
    url: '/Jack614/jalpc_jekyll_theme'
    img: 'static/img/landing/jekyll.jpg'
  angularjs:
    name: 'Jalpc-A'
    url: '/Jack614/Jalpc-A'
    img: 'static/img/landing/angularjs.jpg'

# blog index
index:
  home: 'Home'
  cv: 'CV'
  transcript: 'Transcript'

# donate
donate:
  wechat: 'static/img/pay/404.png'
  alipay: 'static/img/pay/404.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: ''
  public_key: ''

# share
bshare:
  uuid: ''

# baidu analytics
ba:
  uuid: ''

# google analytics
ga:
  id: 'UA-75505537-2'

# blog img path
img_path: '/static/img/blog'

# Build settings
encoding: "utf-8"

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
